### ISSUE TITLE
Sending results to multiple recipients

### ISSUE THREAD

**Issue by thomaschinhm** [cunninghamp/Get-EASDeviceReport.ps1#3]
Hi @cunninghamp ,

Very useful script, thank you.
Is there a way to send the results to multiple recipients?

Thanks in advance,
Thomas

**Comment by cunninghamp** [comment]
Yes, you can send it to a distribution group. That is the simplest way to send it to multiple recipients and allows you to control who gets it by modifying your distribution group membership instead of modifying your command line for running the script.
