### ISSUE TITLE
Device GUID

### ISSUE THREAD

**Issue by thomaschinhm** [cunninghamp/Get-EASDeviceReport.ps1#5]
Is there anyway to include device GUID in the report?

**Comment by cunninghamp** [comment]
Yes, if you know the exact attribute name you want you can pretty easily add it to the attribute that are included in the report.

**Comment by thomaschinhm** [comment]
Do I just add a one line to the below or is there somewhere else I will need to edit as well?:

$stats = @("DeviceID",
            "DeviceAccessState",
            "DeviceAccessStateReason",
            "DeviceModel"
            "DeviceType",
            "DeviceFriendlyName",
            "DeviceOS",
            "LastSyncAttemptTime",
            "LastSuccessSync",
			"guid"

**Comment by cunninghamp** [comment]
Look through the code. Do those attribute names appear anywhere else? If so, then yes. If not, then probably not. You can also make the change you think you need to make, then test it to see the results.
